### ISSUE TITLE
Error Connection refused

### ISSUE THREAD

**Issue by Donsuno** [kramankishore/Knowledge-Graph-Intro#1]
I can't connect and execute:

[['companies', 'create', 'jobs'], ['companies', 'create', 'innovation'], ['Bill Gates', 'supports', 'entrepreneurship']]
{
    "@confidence": "0.35",
    "@policy": "whitelist",
    "@sparql": "",
    "@support": "0",
    "@text": "Startup companies create jobs and innovation. Bill Gates supports entrepreneurship.",
    "@types": "",
    "Resources": [
        {
            "@URI": "http://dbpedia.org/resource/Startup_company",
            "@offset": "0",
            "@percentageOfSecondRank": "0.0",
            "@similarityScore": "1.0",
            "@support": "1796",
            "@surfaceForm": "Startup companies",
            "@types": ""
        },
        {
            "@URI": "http://dbpedia.org/resource/Innovation",
            "@offset": "34",
            "@percentageOfSecondRank": "2.202550246605133E-6",
            "@similarityScore": "0.999997794849095",
            "@support": "3291",
            "@surfaceForm": "innovation",
            "@types": ""
        },
        {
            "@URI": "http://dbpedia.org/resource/Bill_Gates",
            "@offset": "46",
            "@percentageOfSecondRank": "2.813582126385815E-7",
            "@similarityScore": "0.9999997186416009",
            "@support": "2053",
            "@surfaceForm": "Bill Gates",
            "@types": "Http://xmlns.com/foaf/0.1/Person,Wikidata:Q5,Wikidata:Q24229398,Wikidata:Q215627,DUL:NaturalPerson,DUL:Agent,Schema:Person,DBpedia:Person,DBpedia:Agent"
        },
        {
            "@URI": "http://dbpedia.org/resource/Entrepreneurship",
            "@offset": "66",
            "@percentageOfSecondRank": "0.0",
            "@similarityScore": "0.999999999975671",
            "@support": "7525",
            "@surfaceForm": "entrepreneurship",
            "@types": ""
        }
    ]
}
[['', '', ''], ['', '', 'http://dbpedia.org/resource/Innovation'], ['http://dbpedia.org/resource/Bill_Gates', '', 'http://dbpedia.org/resource/Entrepreneurship']]
Data received in graph population:
[['companies', 'create', 'jobs'], ['companies', 'create', 'innovation'], ['Bill Gates', 'supports', 'entrepreneurship']]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 831, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    sop_list_strings, entityLinkTriples)
  File "/Users/doni.suhartono/Documents/GitHub/Knowledge-Graph-Intro/graphPopulation.py", line 42, in popGraph
    subjectTemp = Subject.nodes.first_or_none(subject_name=spo[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/match.py", line 592, in first_or_none
    return self.first(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/match.py", line 578, in first
    result = result = self._get(limit=1, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/match.py", line 542, in _get
    return self.query_cls(self).build_ast()._execute(lazy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/match.py", line 447, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)            
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/util.py", line 32, in wrapper
    _db.set_connection(config.DATABASE_URL)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neomodel/util.py", line 96, in set_connection
    max_pool_size=config.MAX_POOL_SIZE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/__init__.py", line 108, in driver
    return Driver(uri, **config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/__init__.py", line 147, in __new__
    return subclass(uri, **config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/__init__.py", line 221, in __new__
    pool.release(pool.acquire())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/__init__.py", line 218, in connector
    return connect(address, **dict(config, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 962, in connect
    s = _connect(resolved_address, **config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neobolt/direct.py", line 843, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason [Errno 61] Connection refused)

**Comment by motua16** [comment]
I am also facing a similar error.
